[server]
    port = 19000
    secretToken = ""
    registryCron = "0 0/1 * * * ?"
    autoRegistry = true
    adminAddress = "http://127.0.0.1:8088/ecs-container"
    objectId = "11ebc8256d5a46c882573149680305db"
[logConfig]
	level      = ""
    # 日志文件的位置
	filename   = "./k8s-agent.log"
    # 在进行切割之前，日志文件的最大大小（以MB为单位） 
	maxSize    = 200
    # 保留旧文件的最大天数
	maxAge     = 10
     # 保留旧文件的最大个数
	maxBackups = 3  
[auth]
    open = true
    secretToken = "11ebc8256d5a46c882573149680305db"    